version: '2'

services:
    node:
        image: "node:8"
        environment:
          - NODE_ENV=development
          - SERVER_PORT=3000
        user: "node"
        working_dir: /home/node/app
        volumes:
          - ./:/home/node/app
        ports:
            - 8000:3000
        command: bash -c "yarn install && npm start"
